name: release
on:
  push:
    branches:
      - feature/release
  workflow_dispatch:
jobs:
  build_release:
    name: build_release
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}">>$GITHUB_ENV          
      - name: run release
        run:  make release $RELEASE_VERSION
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: "$RELEASE_VERSION"
          tag_name: "$RELEASE_VERSION"
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: "$BUILDDIR/bin/fission-$version-linux-amd64"
          asset_name: Artifact for linux amd64 cli
          asset_content_type: application/gzip
